apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        rajatgupta24/jx-k3s-3: true
        rajatgupta24/quickstart-001: true
        rajatgupta24/quickstart-002: true
        rajatgupta24/quickstart-003: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        rajatgupta24/jx-k3s-3: merge
        rajatgupta24/quickstart-001: merge
        rajatgupta24/quickstart-002: merge
        rajatgupta24/quickstart-003: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - rajatgupta24/jx-k3s-3
        - rajatgupta24/quickstart-001
        - rajatgupta24/quickstart-002
        - rajatgupta24/quickstart-003
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - rajatgupta24/jx-k3s-3
        - rajatgupta24/quickstart-001
        - rajatgupta24/quickstart-002
        - rajatgupta24/quickstart-003
      target_url: http://lighthouse.jx.192.168.29.42.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
